/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 dragon.gltf 
Author: LostBoyz2078 (https://sketchfab.com/LostModels2025)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/dragon-fly-1443a7efe5d5450b8db4c15d8ff5c343
Title: Dragon Fly
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Dragon(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/dragon.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

    useEffect(() => {
    // Play the first animation automatically
    const firstAction = Object.values(actions)[0]
    firstAction?.play()
  }, [actions])

  return (
     <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="GLTF_created_0">
                <primitive object={nodes.GLTF_created_0_rootJoint} />
                <group name="0000_Transport_KA_Skel_96">
                  <group name="0000_Transport_KA_Skel_97" />
                </group>
                <group name="0001_Transport_KA_Skel_98">
                  <group name="0001_Transport_KA_Skel_99" />
                </group>
                <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Tansport_KA01_MI} skeleton={nodes.Object_7.skeleton} />
                <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.Tansport_KA02_MI} skeleton={nodes.Object_10.skeleton} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

 


useGLTF.preload('/dragon.gltf')
