/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 optimized-room.glb 
*/


import { useGLTF } from '@react-three/drei'
import type { JSX } from 'react'
import * as THREE from 'three'

type GLTFResult = {
  nodes: {
    _________6_blinn1_0: THREE.Mesh
    body1_blinn1_0: THREE.Mesh
    cabin_blinn1_0: THREE.Mesh
    chair_body_blinn1_0: THREE.Mesh
    comp_blinn1_0: THREE.Mesh
    emis_lambert1_0: THREE.Mesh
    handls_blinn1_0: THREE.Mesh
    keyboard_blinn1_0: THREE.Mesh
    kovrik_blinn1_0: THREE.Mesh
    lamp_bl_blinn1_0: THREE.Mesh
    lamp_white_blinn1_0: THREE.Mesh
    miuse_blinn1_0: THREE.Mesh
    monitor2_blinn1_0: THREE.Mesh
    monitor3_blinn1_0: THREE.Mesh
    pCylinder5_blinn1_0: THREE.Mesh
    pillows_blinn1_0: THREE.Mesh
    polySurface53_blinn1_0: THREE.Mesh
    radiator_blinn1_0: THREE.Mesh
    radiator_blinn1_0001: THREE.Mesh
    railing_blinn1_0: THREE.Mesh
    red_bttns_blinn1_0: THREE.Mesh
    red_vac_blinn1_0: THREE.Mesh
    stylus_blinn1_0: THREE.Mesh
    table_blinn1_0: THREE.Mesh
    tablet_blinn1_0: THREE.Mesh
    triangle_blinn1_0: THREE.Mesh
    vac_black_blinn1_0: THREE.Mesh
    vacuum1_blinn1_0: THREE.Mesh
    vacuumgrey_blinn1_0: THREE.Mesh
    vires_blinn1_0: THREE.Mesh
    window_blinn1_0: THREE.Mesh
    window4_phong1_0: THREE.Mesh
  }
  materials: {
    blinn1: THREE.MeshStandardMaterial
    lambert1: THREE.MeshStandardMaterial
    phong1: THREE.MeshStandardMaterial
  }
}


export default function Room(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/optimized-room.glb') as unknown as GLTFResult
  
  return (
    <group {...props} dispose={null}>
      <mesh  matrixAutoUpdate={false} geometry={nodes._________6_blinn1_0.geometry} material={new THREE.MeshLambertMaterial({ color: "gray" })} />
      <mesh  matrixAutoUpdate={false} geometry={nodes.body1_blinn1_0.geometry} material={new THREE.MeshLambertMaterial({ color: "#aaa" })} />
      <mesh  matrixAutoUpdate={false} geometry={nodes.cabin_blinn1_0.geometry} material={new THREE.MeshLambertMaterial({ color: "white" })} />
      <mesh  matrixAutoUpdate={false} geometry={nodes.chair_body_blinn1_0.geometry} material={materials.blinn1} />
      <mesh  matrixAutoUpdate={false} geometry={nodes.comp_blinn1_0.geometry} material={new THREE.MeshLambertMaterial({ color: "white" })} />
      <mesh  matrixAutoUpdate={false} geometry={nodes.emis_lambert1_0.geometry} material={materials.lambert1} />
      <mesh  matrixAutoUpdate={false} geometry={nodes.handls_blinn1_0.geometry} material={materials.blinn1} />
      <mesh  matrixAutoUpdate={false} geometry={nodes.keyboard_blinn1_0.geometry} material={materials.blinn1} />
      <mesh  matrixAutoUpdate={false} geometry={nodes.kovrik_blinn1_0.geometry} material={materials.blinn1} />
      <mesh  matrixAutoUpdate={false} geometry={nodes.lamp_bl_blinn1_0.geometry} material={materials.blinn1} />
      <mesh  matrixAutoUpdate={false} geometry={nodes.lamp_white_blinn1_0.geometry} material={materials.blinn1} />
      <mesh  matrixAutoUpdate={false} geometry={nodes.miuse_blinn1_0.geometry} material={materials.blinn1} />
      <mesh  matrixAutoUpdate={false} geometry={nodes.monitor2_blinn1_0.geometry} material={materials.blinn1} />
      <mesh  matrixAutoUpdate={false} geometry={nodes.monitor3_blinn1_0.geometry} material={materials.blinn1} />
      <mesh  matrixAutoUpdate={false} geometry={nodes.pCylinder5_blinn1_0.geometry} material={materials.blinn1} />
      <mesh  matrixAutoUpdate={false} geometry={nodes.pillows_blinn1_0.geometry} material={new THREE.MeshLambertMaterial({ color: "white" })} />
      <mesh  matrixAutoUpdate={false} geometry={nodes.polySurface53_blinn1_0.geometry} material={materials.blinn1} />
      <mesh  matrixAutoUpdate={false} geometry={nodes.radiator_blinn1_0.geometry} material={materials.blinn1} />
      <mesh  matrixAutoUpdate={false} geometry={nodes.radiator_blinn1_0001.geometry} material={materials.blinn1} />
      <mesh  matrixAutoUpdate={false} geometry={nodes.railing_blinn1_0.geometry} material={new THREE.MeshLambertMaterial({ color: "white" })} />
      <mesh  matrixAutoUpdate={false} geometry={nodes.red_bttns_blinn1_0.geometry} material={materials.blinn1} />
      <mesh  matrixAutoUpdate={false} geometry={nodes.red_vac_blinn1_0.geometry} material={materials.blinn1} />
      <mesh  matrixAutoUpdate={false} geometry={nodes.stylus_blinn1_0.geometry} material={materials.blinn1} />
      <mesh  matrixAutoUpdate={false} geometry={nodes.table_blinn1_0.geometry} material={new THREE.MeshLambertMaterial({ color: "white" })} />
      <mesh  matrixAutoUpdate={false} geometry={nodes.tablet_blinn1_0.geometry} material={materials.blinn1} />
      <mesh  matrixAutoUpdate={false} geometry={nodes.triangle_blinn1_0.geometry} material={materials.blinn1} />
      <mesh  matrixAutoUpdate={false} geometry={nodes.vac_black_blinn1_0.geometry} material={materials.blinn1} />
      <mesh  matrixAutoUpdate={false} geometry={nodes.vacuum1_blinn1_0.geometry} material={materials.blinn1} />
      <mesh  matrixAutoUpdate={false} geometry={nodes.vacuumgrey_blinn1_0.geometry} material={materials.blinn1} />
      <mesh  matrixAutoUpdate={false} geometry={nodes.vires_blinn1_0.geometry} material={materials.blinn1} />
      <mesh  matrixAutoUpdate={false} geometry={nodes.window_blinn1_0.geometry} material={new THREE.MeshLambertMaterial({ color: "white" })} />
      <mesh  matrixAutoUpdate={false} geometry={nodes.window4_phong1_0.geometry} material={new THREE.MeshLambertMaterial({ color: "black" })} />
    </group>
  )
}

useGLTF.preload('/models/optimized-room.glb')
